config/routes.rb
Rails.application.routes.draw do


  resources :orders
  resources :line_items
  resources :carts
  resources :cameras do
    get :who_bought, on: :member
  end
  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  root 'cameras#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer mt6">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>B.U.Gs</strong> by <a href="#">Hadi Khalili</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar pale-orange">
<div class="container is-fuid">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-1">BUGs<br><span><h6 class="subtitle si-6">Buy Used Gears</h6></span></h1>
    <% end %>
  </div>
    
  <div class="navbar-menu is-active">
    <div class="navbar-end">
      <% if user_signed_in? %>
        <%= link_to 'Sell', new_camera_path, class: "navbar-item" %>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to "Account", edit_user_registration_path, class: "navbar-link" %>
          <div class="navbar-dropdown is-right">
            <%= link_to current_user.name, edit_user_registration_path, class: "navbar-item" %>
            <%= link_to "My Products", cameras_path, class: "navbar-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-item" %>
          </div>
        </div>
        <%= link_to current_user.name, edit_user_registration_path, class: "navbar-item" %>        
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "navbar-item"%>
        <%= link_to 'Register', new_user_registration_path, class: "navbar-item"%>
      <% end %>

      <% if cart_has_items %>
      <%= link_to cart_path(@cart), class:"navbar-item" do %>
          <span class="icon is-small">
            <i class="fa fa-shopping-cart"></i>
          </span>
          <span>Cart
            <%= cart_count_over_one %>
          </span>
          <% end %>
      <% else %>
        <%= link_to cameras_path, class:"navbar-item" do %>
        <span class="icon is-small">
          <i class="fa fa-shopping-cart"></i>
        </span>
        <span>Cart 0 </span>
        <% end %>
      <% end %>

      </div>
  </div>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
      
    </div>

    <%= render "layouts/footer" %>
    
   

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>